### ISSUE TITLE
Página de rooms no carga

### ISSUE THREAD

**Issue by Fenho** [IIC3745-Grupo-5/ProyectoB#5]
Al ingresar al show de un room, esta vista no carga inmediatamente, pero extrañamente si carga cuando uno actualiza la página.

**Comment by dasolari** [comment]
Voy a ver como solucionarlo, pero creo que es un problema con el uso de `turbolinks` para cargar más rápido el contenido de las páginas.

**Comment by dasolari** [comment]
Problema solucionado.
